#!/bin/sh -e

echo "System Rescue CD" >&2

. /usr/share/grub/grub-mkconfig_lib

if [ -r /etc/default/systemrescuecd ] ; then
  . /etc/default/systemrescuecd
fi

ls /boot/systemrescuecd/systemrescuecd*.iso --sort=version 2>/dev/null |
tail -n1 |
while read ISO ; do
    device=$(${grub_probe} --target=device "${ISO}")
    device_label=$(${grub_probe} --target=fs_label "${ISO}")
    path=$(make_system_path_relative_to_its_root "${ISO}")
    grub_string=$(prepare_grub_to_access_device "${device}" | grub_add_tab | grub_add_tab)
    cat << EOF
menuentry "System Rescue CD" --class rescue {
${grub_string}
    set isofile=${path}
    loopback loop \${isofile}
    echo   'Loading System Rescue CD kernel ...'
    linux  (loop)/sysresccd/boot/x86_64/vmlinuz img_label=${device_label} img_loop=${path} archisobasedir=sysresccd ${CUSTOM_BOOTOPTIONS}
    echo   'Loading System Rescue CD initramfs ...'
    initrd (loop)/sysresccd/boot/x86_64/sysresccd.img
}
EOF
done
